<?php
    namespace App\System\Router;

    use Psr\Http\Message\ServerRequestInterface;
    use Psr\Http\Message\ResponseInterface;
    use Psr\Http\Server\MiddlewareInterface;
    use Psr\Http\Server\RequestHandlerInterface;

    class MiddlewaresDispatcher implements RequestHandlerInterface
    {
        /**
         * @var array $middlewares The list of middlewares to be dispatched.
         */
        private array $middlewares;

        /**
         * @var RequestHandlerInterface $finalHandler The final handler to be called after all middlewares.
         */
        private RequestHandlerInterface $finalHandler;

        /**
         * Constructor for the MiddlewaresDispatcher class.
         *
         * @param array $middlewares The list of middlewares to be dispatched.
         * @param RequestHandlerInterface $finalHandler The final handler to be called after all middlewares.
         */
        public function __construct(array $middlewares, RequestHandlerInterface $finalHandler)
        {
            $this->middlewares = $middlewares;
            $this->finalHandler = $finalHandler;
        }

        /**
         * Handle the incoming request by dispatching the middlewares.
         *
         * @param ServerRequestInterface $request The incoming server request.
         * @return ResponseInterface The response generated by the middlewares or the final handler.
         */
        public function handle(ServerRequestInterface $request): ResponseInterface
        {
            return $this->dispatch(0, $request);
        }

        /**
         * Dispatch the middleware at the given index.
         *
         * @param int $index The index of the middleware to dispatch.
         * @param ServerRequestInterface $request The incoming server request.
         * @return ResponseInterface The response generated by the middleware or the final handler.
         */
        public function dispatch(int $index, ServerRequestInterface $request): ResponseInterface
        {
            if(!isset($this->middlewares[$index])) {
                //If there is no more middleware, call the final handler
                return $this->finalHandler->handle($request);
            }

            $middleware = new $this->middlewares[$index];

            //Builds a handler that calls the next middleware
            $nextHandler = new class($this, $index + 1) implements RequestHandlerInterface {
                private MiddlewaresDispatcher $dispatcher;
                private int $nextIndex;

                public function __construct(MiddlewaresDispatcher $dispatcher, int $nextIndex)
                {
                    $this->dispatcher = $dispatcher;
                    $this->nextIndex = $nextIndex;
                }

                public function handle(ServerRequestInterface $request): ResponseInterface
                {
                    return $this->dispatcher->dispatch($this->nextIndex, $request);
                }
            };

            return $middleware->process($request, $nextHandler);
        }
    }